image: gitpod/workspace-full-vnc

ports:
  - port: 35900
  - port: 5900
  - port: 6080

tasks:
  - init: pip3 install -r requirements.txt
  - init: git config core.hooksPath hooks
  - init: find ./hooks -type f -exec chmod +x {} \;
  
github:
  prebuilds:
    master: true
